# fly.toml app configuration file generated for fulltack-quarkus-still-silence-5029 on 2024-07-21T12:07:37-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fulltack-quarkus-still-silence-5029'
primary_region = 'gru'

[build]
  dockerfile = 'src/main/docker/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
