name:  Deploy to fly
on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: development
        steps:
        - uses: actions/checkout@v4
          name: Checkout code
        - name: Download fly
          run: curl -L https://fly.io/install.sh | sh
        - name: Set environment for fly
          run:  |
               export FLYCTL_INSTALL="/home/runner/.fly"
              export PATH="$FLYCTL_INSTALL/bin:$PATH"
        - name: Deploy to fly
          run: fly deploy
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
