name:  Deploy to fly
on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Maven Action
          uses: s4u/setup-maven-action@v1.14.0
          run: mvn package

    deploy:
        runs-on: ubuntu-latest
        environment: development
        steps:
        - uses: actions/checkout@v4
          name: Checkout code
        - name: Download fly
          run: curl -L https://fly.io/install.sh | sh
        - name: Set environment for fly
          run: |
            export PATH="$HOME/.fly/bin:$PATH"
            echo "$HOME/.fly/bin" >> $GITHUB_PATH
        - name: Deploy to fly
          run: fly deploy
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
