on:
  push:
    branches:
      - main
jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push Docker image with commit ID
          run: |
            # Get the latest commit SHA
            commit_sha=$(git rev-parse --short HEAD)
            
            # Build the image with a tag that includes the commit ID
            docker buildx build --push --tag ghcr.io/${{ github.repository_owner }}/quarkus-fullstack-angular:${commit_sha} --context src/main/docker .

